Fix workflow

diff --git a/.github/workflows/doc.yml b/.github/workflows/doc.yml
--- a/.github/workflows/doc.yml
+++ b/.github/workflows/doc.yml
@@ -1,46 +1,30 @@
-name: release
-on:
+name: "Deploy docs"
+on: 
   push:
     branches:
-    - main
-
+    - main 
 jobs:
-  release:
-    name: Build
+  docs:
     runs-on: ubuntu-latest
-    if: "!contains(github.event.head_commit.message, 'auto rebuilding site')"
     steps:
-    - name: Checkout
-      uses: actions/checkout@v2
+    - uses: actions/checkout@v1
+    - uses: ammaraskar/sphinx-action@master
       with:
-        ref: "master"
-
-    - name: Set up Python
-      uses: actions/setup-python@v1
+        docs-folder: "docs/"
+    - name: Commit documentation changes
+      run: |
+        git clone https://github.com/adaptor-lang/adaptor.git --branch gh-pages --single-branch gh-pages
+        cp -r docs/_build/html/* gh-pages/
+        cd gh-pages
+        git config --local user.email "action@github.com"
+        git config --local user.name "GitHub Action"
+        git add .
+        git commit -m "Update documentation" -a || true
+        # The above command will fail if no changes were present, so we ignore
+        # the return code.
+    - name: Push changes
+      uses: ad-m/github-push-action@master
       with:
-        python-version: 3.7
-
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install -r docs/requirements.txt
-    - name: Build
-      run: |
-        sphinx-build -M html docs dist 
-    - name: Deploy Configuration
-      run: |
-          mkdir ~/.ssh
-          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
-          echo "${{ secrets.ACTIONS_DEPLOY_KEY }}" > ~/.ssh/id_rsa
-          chmod 400 ~/.ssh/id_rsa
-    - name: Push
-      env:
-        GITHUB_USER: "builduser"
-        GITHUB_EMAIL: "test-builduser@sample.com"
-      run: |
-          git config --local user.name "${GITHUB_USER}"
-          git config --local user.email "${GITHUB_EMAIL}"
-          git remote set-url origin git@github.com:${GITHUB_REPOSITORY}.git
-          git add docs
-          git commit -m "auto rebuilding site"
-          git push origin main 
+        branch: gh-pages
+        directory: gh-pages
+        github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
